import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_ENDPOINT = os.getenv("OPENAI_ENDPOINT")
AZURE_IMAGE_CAPTIONING_API_KEY = os.getenv("AZURE_IMAGE_CAPTIONING_API_KEY")
UPLOAD_FILE_PATH = os.getenv("UPLOAD_FILE_PATH")